### ISSUE TITLE
Error 1 while uploading firmware

### ISSUE THREAD

**Issue by redfusion83** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#555]
So I followed the installation manual, the only change I made was changing board to "d1_mini".
When I try to upload the firmware to the D1 on Win11 I get "Error 1".
Here's the Log:
```
Building in release mode
Retrieving maximum program size .pio\build\nodemcuv2\firmware.elf
Checking size .pio\build\nodemcuv2\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=====     ]  54.3% (used 44444 bytes from 81920 bytes)
Flash: [======    ]  64.6% (used 674756 bytes from 1044464 bytes)
Configuring upload protocol...
AVAILABLE: espota, esptool
CURRENT: upload_protocol = esptool
Looking for upload port...
Auto-detected: COM5
Uploading .pio\build\nodemcuv2\firmware.bin
esptool.py v3.0
Serial port COM5
Connecting....
Traceback (most recent call last):
  File "C:\Users\i_am_root\.platformio\packages\tool-esptoolpy\esptool.py", line 3969, in <module>
    _main()
  File "C:\Users\i_am_root\.platformio\packages\tool-esptoolpy\esptool.py", line 3962, in _main
    main()
  File "C:\Users\i_am_root\.platformio\packages\tool-esptoolpy\esptool.py", line 3552, in main
    esp.connect(args.before, args.connect_attempts)
  File "C:\Users\i_am_root\.platformio\packages\tool-esptoolpy\esptool.py", line 519, in connect
    last_error = self._connect_attempt(mode=mode, esp32r0_delay=False)
  File "C:\Users\i_am_root\.platformio\packages\tool-esptoolpy\esptool.py", line 499, in _connect_attempt
    self.sync()
  File "C:\Users\i_am_root\.platformio\packages\tool-esptoolpy\esptool.py", line 437, in sync
    self.command(self.ESP_SYNC, b'\x07\x07\x12\x20' + 32 * b'\x55',
  File "C:\Users\i_am_root\.platformio\packages\tool-esptoolpy\esptool.py", line 398, in command
    raise UnsupportedCommandError(self, op)
__main__.UnsupportedCommandError: Invalid (unsupported) command 0x8
*** [upload] Error 1
========================================================================================== [FAILED] Took 3.51 seconds ==========================================================================================

 *  The terminal process "C:\Users\i_am_root\.platformio\penv\Scripts\platformio.exe 'run', '--target', 'upload', '--environment', 'nodemcuv2'" terminated with exit code: 1. 
```
Any tips on where to go from here?

**Comment by redfusion83** [comment]
I solved it already. Seems like there is something wrong with the D1 board. I tried a different one - worked. Maybe it was faulty, because it was brand new. Good luck I had another one!
